CREATE DATABASE IF NOT EXISTS DAPP;
USE DAPP;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER'
);
CREATE TABLE IF NOT EXISTS logged_in_users (
  session_id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  login_time DATETIME NOT NULL
 
);



